# Generated by Django 2.1.3 on 2018-11-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_id', models.IntegerField(blank=True, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_impact', models.CharField(blank=True, max_length=255, null=True)),
                ('security_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('consequence_severity', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_level', models.CharField(blank=True, max_length=255, null=True)),
                ('followup_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('incident_closed', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_resolution_in_days', models.IntegerField(blank=True, null=True)),
                ('open_month', models.CharField(blank=True, max_length=255, null=True)),
                ('open_year', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_month', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_year', models.CharField(blank=True, max_length=255, null=True)),
                ('open_month_create_time', models.CharField(blank=True, max_length=255, null=True)),
                ('open_year_create_time', models.CharField(blank=True, max_length=255, null=True)),
                ('malware_detected', models.CharField(blank=True, max_length=255, null=True)),
                ('source_of_logs', models.CharField(blank=True, max_length=255, null=True)),
                ('host_info', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp_arcsight', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloDeDadosUnificados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('incident_code', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_ci', models.CharField(blank=True, max_length=255, null=True)),
                ('security_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('info_security_typification', models.CharField(blank=True, max_length=255, null=True)),
                ('afected_user', models.CharField(blank=True, max_length=255, null=True)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('impact', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'modelo_de_dados_unificados',
                'managed': False,
            },
        ),
    ]
