"""
Django settings for official_django_tutorial project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kha3)1idskun_4!c53*u@xalsrkcwfp*kf&^1700f@zyw@#3t#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'official_django_tutorial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS is a list of filesystem directories to check when
        # loading Django templates; it’s a search path.
        # after creating the "templates" folder specify where it is
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'official_django_tutorial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


"""
    By default, the configuration uses SQLite. I
    f you’re new to databases, or you’re just interested in trying Django,
    this is the easiest choice. SQLite is included in Python, so you won’t
    need to install anything else to support your database.
    When starting your first real project, however, you may want to
    use a more robust database like PostgreSQL, to avoid database-switching
    headaches down the road.

    If you wish to use another database, install the appropriate database bindings,
    and change the following keys in the DATABASES 'default' item to match your
    database connection settings:

    ENGINE – Either 'django.db.backends.sqlite3',
                    'django.db.backends.postgresql_psycopg2',
                    'django.db.backends.mysql', or
                    'django.db.backends.oracle'.
    Other backends are also available.

    NAME – The name of your database.

    If you’re using SQLite, the database will be a file on your computer;
    in that case, NAME should be the full absolute path,
    including filename, of that file.
    The default value,
        os.path.join(BASE_DIR, 'db.sqlite3'),
    will store the file in your project directory.

    If you are not using SQLite as your database,
    additional settings such as USER, PASSWORD, HOST must be added.
    For more details, see the reference documentation for DATABASES.
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
